# Generated by Django 3.0.3 on 2020-02-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type_place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
